services:
  survey_api:
    image: survey_api
    build:
      context: .
      dockerfile: SurveyMinimalApi/Dockerfile
    depends_on:
      - survey_db
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=123;Host=survey_db;Port=5432;Database=survey_db;
    networks:
      - survey_network

  survey_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "survey_db"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./SurveyMinimalApi/Data:/docker-entrypoint-initdb.d/  
    networks:
      - survey_network

networks:
  survey_network:
    driver: bridge

volumes:
  postgres_data:
